#!/bin/sh
#############
### FLAGS ###
#############
# Flags for privacy
flags_custom="--disable-3d-apis --disable-background-networking --disable-breakpad --disable-oopr-debug-crash-dump --disable-speech-api --disable-sync --disable-system-font-check --no-crash-upload"

# Flags to enable wayland support
flags_wayland="--enable-features=UseOzonePlatform --ozone-platform=wayland"

###################
### DIRECTORIES ###
###################
# Chromium configuration directory
home_config_chromium="$HOME/.config/chromium";

# If the directory does not already exist, then create it
[[ ! -d "$home_config_chromium" ]] && mkdir "$home_config_chromium";

#############
### LABEL ###
#############
# Restore the SELinux labels for the specified directories if necessary
/usr/sbin/restorecon -Rv $HOME/{.cache/chromium,.config/chromium};

#############
### START ###
#############
/usr/bin/chromium-browser $flags_custom $flags_wayland --incognito "$@";
