#!/bin/sh
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libdcerpc-binding.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libdcerpc-server-core.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libdcerpc.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libndr-krb5pac.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libndr-nbt.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libndr-standard.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libndr.so.2";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libnetapi.so.1";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libsamba-credentials.so.1";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libsamba-errors.so.1";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libsamba-hostconfig.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libsamba-passdb.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libsamba-util.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libsamdb.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libsmbconf.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libsmbldap.so.2";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/libtevent-util.so.0";
/usr/sbin/semanage fcontext --add --type samba-client-libs_t "/usr/lib/samba(.*)?";
