#!/bin/sh
#################
### FUNCTIONS ###
#################
function try_mkdir() {
    [[ ! -d "$1" ]] && mkdir "$1";
};

###################
### DIRECTORIES ###
###################
# Configuration directory for mpv
home_config_mpv="$HOME/.config/mpv";

# Music directory
home_music="$HOME/Music";

# If the above directories do not exist, then create them
try_mkdir "$home_config_mpv";
try_mkdir "$home_music";

#############
### LABEL ###
#############
# Restore the SELinux labels for the specified directories if necessary
/usr/sbin/restorecon -Rv {"$home_config_mpv","$home_music"};

#############
### START ###
#############
/usr/bin/mpv "$@";
