#!/bin/sh
###################
### DIRECTORIES ###
###################
home_mozilla="${HOME}/.mozilla";
home_thunderbird="${HOME}/.thunderbird";
cache_thunderbird="${HOME}/.cache/thunderbird";

#############
### LABEL ###
#############
function label() {
    [[ -d "${1}" ]] && /usr/sbin/restorecon -Rv "${1}";
};

# Restore the SELinux labels for the specified directories if necessary
label "${home_mozilla}";
label "${home_thunderbird}";
label "${cache_thunderbird}";

#############
### START ###
#############
if [ -z "${WAYLAND_DISPLAY}" ]; then
    # If the wayland display variable is empty, then start Mozilla Thunderbird on X
    /usr/bin/thunderbird "${@}";
else
    # Otherwise, start Mozilla Thunderbird on wayland
    MOZ_ENABLE_WAYLAND=1 /usr/bin/thunderbird "${@}";
fi;
