#!/bin/sh

#############
### START ###
#############
/usr/bin/youtube-dl "${@}";

#############
### LABEL ###
#############
# Fix the SELinux labels for the downloaded files silently
/usr/sbin/restorecon -R "${HOME}";
