#!/bin/sh
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/ca/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/da/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/de/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/es/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/fi/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/fr/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/id/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/it/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/ja/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/ko/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/ms/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/nl/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/pl/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/pt/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/pt_BR/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/sv/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/vi/LC_MESSAGES/gawk.mo";
/usr/sbin/semanage fcontext --add --type gawk-all-langpacks_usr_t "/usr/share/locale/zh_CN/LC_MESSAGES/gawk.mo";
